import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { getPages } from "@/sanity/utils";
import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "My awesome site",
  description: "Generated by Next + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get all of our pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="no-scrollbar">
        <Navbar pages={pages} />
        <main className="mx-auto max-w-7xl p-6 lg:px-8 py-20">{children}</main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
